import turtle
from math import sin, cos, pi, radians
turtle.penup()
turtle.goto(100,0)
turtle.pendown()
turtle.color('yellow')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.penup()
turtle.goto(60,120)
turtle.color('blue')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(140,120)
turtle.color('blue')
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.up()               
turtle.goto(90, 100)        
turtle.down()             
turtle.color('black')
turtle.left(90)
turtle.pensize(8)         
turtle.left(180)          
turtle.forward(50)
t.up()               
t.goto(70, -10)      
t.color('red')       
t.down()             
t.circle(-70, 180, 30)   


